databases:
  - name: inmuebles
    databaseName: inmuebles
    user: star

services:
  - type: web
    name: inmuebles
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn inmuebles.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inmuebles
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4